- name: ensure tmux is installed
  become: yes
  pacman:
    name: tmux
    state: present

- name: ensure needed directories exist
  file:
    path: $HOME/.config/systemd/user
    state: directory

- name: deploy unit from template
  become: yes
  copy:
    src: tmux.service
    dest: /home/{{ansible_user}}/.config/systemd/user/tmux.service
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"

- name: Ensure lingering enabled
  become: yes
  command:
    cmd: loginctl enable-linger "{{ ansible_user }}"
    creates: "/var/lib/systemd/linger/{{ ansible_user }}"

- name: reload systemd daemon to make new unit available
  systemd:
    scope: user
    daemon_reload: yes

- name: enable and start tmux user-service
  command:
    cmd: systemctl --user enable --now tmux
